# https://github.com/DavidAnson/markdownlint#optionsconfig
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Bare URL are OK
MD034: false

# https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md046---code-block-style
MD046:
  # default style 'indented' prevents setting code block language
  style: "consistent"

MD013:
  line_length: 4096
  strict: false
  stern: false
