# https://github.com/DavidAnson/markdownlint#optionsconfig
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Bare URL are OK
MD034: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md046---code-block-style
# style: "indented" prevents setting code block language
# style: "fenced" enforces ``` and thus prevents indenting, which is nicer to read in raw ASCII where posible
# style: "consistent" prevents mixing indenting (without code block language) and fenced with code block language, which is useful
MD046: false

MD013:
  line_length: 4096
  strict: false
  stern: false
