# https://kind.sigs.k8s.io/docs/user/configuration/ for https://www.sidero.dev
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sidero
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 69
    hostPort: 69
    listenAddress: "0.0.0.0"
    protocol: UDP
  - containerPort: 8081
    hostPort: 8081
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 51821
    hostPort: 51821
    listenAddress: "0.0.0.0"
    protocol: UDP
